USE DW_Vestibular
-- CANDIDATO INÍCIO
CREATE TABLE DIM_CANDIDATO (
	SK_CANDIDATO INT NOT NULL,
	NK_CANDIDATO INT NOT NULL,
	NM_CANDIDATO VARCHAR(50) NOT NULL,
	ETL_VERSAO INT NOT NULL,
	ETL_DT_INICIO DATETIME NOT NULL,
	ETL_DT_FIM DATETIME NOT NULL,
	CONSTRAINT SK_CANDIDATO PRIMARY KEY (SK_CANDIDATO)
)

SELECT * FROM DIM_CANDIDATO

INSERT INTO DIM_CANDIDATO VALUES (
  0,
  -1,
  'NA',
  -1,
  '1900-01-01 00:00:00.000',
  '9999-01-01 23:59:59.000'
 )

-- CANDIDATO FIM

-- CURSO INÍCIO
CREATE TABLE DIM_CURSO (
	SK_CURSO INT NOT NULL,
	NK_CURSO INT NOT NULL,
	NM_CURSO VARCHAR(50) NOT NULL,
	ELT_VERSAO INT NOT NULL,
	ETL_DT_INICIO DATETIME NOT NULL,
	ETL_DT_FIM DATETIME NOT NULL,
	CONSTRAINT SK_CURSO PRIMARY KEY (SK_CURSO)
)

SELECT * FROM DIM_CURSO

INSERT INTO DIM_CURSO VALUES (
  0,
  -1,
  'NA',
  -1,
  '1900-01-01 00:00:00.000',
  '9999-01-01 23:59:59.000'
 )
-- CURSO FIM

-- PROCESSO INÍCIO
CREATE TABLE DIM_PROCESSO (
    SK_PROCESSO INT NOT NULL,
	NK_PROCESSO INT NOT NULL,
    NM_PROCESSO VARCHAR(50) NOT NULL,
    PERIODO_LETIVO VARCHAR(10) NOT NULL,
    ETL_VERSAO INT NOT NULL,
    ETL_DT_INICIO DATETIME NOT NULL,
    ETL_DT_FIM DATETIME NOT NULL,
    CONSTRAINT SK_PROCESSO PRIMARY KEY (SK_PROCESSO)
)

SELECT * FROM DIM_PROCESSO
INSERT INTO DIM_PROCESSO VALUES (
  0,
  -1,
  'NA',
  'NA',
  -1,
  '1900-01-01 00:00:00.000',
  '9999-01-01 23:59:59.000'
 )
 -- PROCESSO FIM

-- FORMA P INÍCIO

CREATE TABLE DIM_FORMA_PAGTO (
	SK_FORMA_PAGTO INT NOT NULL,
	NK_FORMA_PAGTO INT NOT NULL,
	NM_FORMA_PAGTO VARCHAR(50) NOT NULL,
	ETL_VERSAO INT NOT NULL,
	ETL_DT_INICIO DATETIME NOT NULL,
	ETL_DT_FIM DATETIME NOT NULL,
	CONSTRAINT SK_FORMA_PAGTO PRIMARY KEY (SK_FORMA_PAGTO)
)

SELECT * FROM DIM_FORMA_PAGTO
INSERT INTO DIM_FORMA_PAGTO VALUES (
  0,
  -1,
  'NA',
  -1,
  '1900-01-01 00:00:00.000',
  '9999-01-01 23:59:59.000'
 )

-- FORMA P FIM

-- DATA INÍCIO
CREATE TABLE DIM_DATA(
	SK_DATA VARCHAR(10) PRIMARY KEY NOT NULL,
	DATA DATE NOT NULL,
	COD_SEMANA INT NOT NULL,
	DIA_SEMANA INT NOT NULL,
	NOME_DIA_SEMANA VARCHAR(20) NOT NULL,
	DIA INT NOT NULL,
	MES INT NOT NULL,
	NOME_MES VARCHAR(20) NOT NULL,
	MES_ANO VARCHAR(12) NOT NULL,
	NOME_MES_ANO VARCHAR(30) NOT NULL,
	TRIMESTRE INT NOT NULL,
	NOME_TRIMESTRE VARCHAR(20) NOT NULL,
	TRIMESTRE_ANO VARCHAR(12) NOT NULL,
	NOME_TRIMESTRE_ANO VARCHAR(30) NOT NULL,
	SEMESTRE INT NOT NULL,
	NOME_SEMESTRE VARCHAR(20) NOT NULL,
	SEMESTRE_ANO VARCHAR(12) NOT NULL,
	NOME_SEMESTRE_ANO VARCHAR(30) NOT NULL,
	ANO INT NOT NULL,
	TIPO_DIA VARCHAR(20) NOT NULL
)

SELECT * FROM DIM_DATA

--DROP PROCEDURE SP_INSERT_DIM_DATA

CREATE PROCEDURE SP_INSERT_DIM_DATA
	@DATAINICIAL DATE, @DATAFINAL DATE
AS
BEGIN
	DECLARE 
	@SK_DATA VARCHAR(10),
	@DATA DATE,
	@COD_SEMANA INT,
	@DIA_SEMANA INT,
	@NOME_DIA_SEMANA VARCHAR(20),
	@DIA INT,
	@MES INT,
	@NOME_MES VARCHAR(20),
	@MES_ANO VARCHAR(12),
	@NOME_MES_ANO VARCHAR(30),
	@TRIMESTRE INT,
	@NOME_TRIMESTRE VARCHAR(20),
	@TRIMESTRE_ANO VARCHAR(12),
	@NOME_TRIMESTRE_ANO VARCHAR(30),
	@SEMESTRE INT,
	@NOME_SEMESTRE VARCHAR(20),
	@SEMESTRE_ANO VARCHAR(12),
	@NOME_SEMESTRE_ANO VARCHAR(30),
	@ANO INT,
	@TIPO_DIA VARCHAR(20)

	WHILE @DATAINICIAL <= @DATAFINAL
	BEGIN
		SET @SK_DATA = FORMAT(@DATAINICIAL, 'yyyyMMdd')
		SET @DATA = @DATAINICIAL
		SET @COD_SEMANA =DATEPART(WEEK, @DATA)
		SET @DIA_SEMANA = DATEPART(WEEKDAY, @DATA)
		SET @NOME_DIA_SEMANA =
			CASE 
				WHEN @DIA_SEMANA = '1' THEN 'Domingo'
				WHEN @DIA_SEMANA = '2' THEN 'Segunda'
				WHEN @DIA_SEMANA = '3' THEN 'Terça'
				WHEN @DIA_SEMANA = '4' THEN 'Quarta'
				WHEN @DIA_SEMANA = '5' THEN 'Quinta'
				WHEN @DIA_SEMANA = '6' THEN 'Sexta'
				ELSE 'Sábado'
			END
		SET @DIA = DAY(@DATA)
		SET @MES= MONTH(@DATA)
		SET @NOME_MES = 
			CASE
				WHEN @MES =  '1' THEN 'Janeiro'
				WHEN @MES =  '2' THEN 'Fevereiro'
				WHEN @MES =  '3' THEN 'Março'
				WHEN @MES =  '4' THEN 'Abril'
				WHEN @MES =  '5' THEN 'Maio'
				WHEN @MES =  '6' THEN 'Junho'
				WHEN @MES =  '7' THEN 'Julho'
				WHEN @MES =  '8' THEN 'Agosto'
				WHEN @MES =  '9' THEN 'Setembro'
				WHEN @MES = '10' THEN 'Outubro'
				WHEN @MES = '11' THEN 'Novembro'
				ELSE 'Dezembro'
			END
		SET @MES_ANO = CONCAT(CONVERT(CHAR(2), @DATA, 101),' - ',YEAR(@DATA)) -- 01-2021
		SET @NOME_MES_ANO = CONCAT(@NOME_MES, ' - ',YEAR(@DATA))-- Janeiro 2021 
		SET @TRIMESTRE = 
			CASE	
				WHEN @MES IN (1,2,3) THEN 1
				WHEN @MES IN (4,5,6) THEN 2
				WHEN @MES IN (7,8,9) THEN 3
				ELSE 4
			END
		SET @NOME_TRIMESTRE =
		CASE
			WHEN @TRIMESTRE = 1 THEN 'Primeiro Trimestre'
			WHEN @TRIMESTRE = 2 THEN 'Segundo Trimestre'
			WHEN @TRIMESTRE = 3 THEN 'Terceiro Trimestre'
			ELSE 'Quarto Trimestre'
		END
		SET @TRIMESTRE_ANO = CONCAT(CONCAT('0',CONVERT(CHAR(2), @TRIMESTRE)),'- ',YEAR(@DATA))-- 01-2021
		SET @NOME_TRIMESTRE_ANO = CONCAT(@NOME_TRIMESTRE, ' ',YEAR(@DATA)) --Terceiro Trimestre 2021 
		SET @SEMESTRE = IIF(@MES IN(1,2,3,4,5,6),1,2)
		SET @NOME_SEMESTRE = IIF(@SEMESTRE IN(1), 'Primeiro Semestre', 'Segundo Semestre')
		SET @SEMESTRE_ANO = CONCAT(CONCAT('0',CONVERT(CHAR(2), @SEMESTRE)),'- ',YEAR(@DATA))
		SET @NOME_SEMESTRE_ANO = CONCAT(@NOME_SEMESTRE, ' ', YEAR(@DATA)) --Segundo Semestre 2021
		SET @ANO = YEAR(@DATA)
		SET @TIPO_DIA = IIF(@DIA_SEMANA IN(1,7),'Dia não Útil','Dia Útil')

		INSERT INTO DIM_DATA
			SELECT	
				@SK_DATA,
				@DATA,
				@COD_SEMANA,
				@DIA_SEMANA,
				@NOME_DIA_SEMANA,
				@DIA,
				@MES,
				@NOME_MES,
				@MES_ANO,
				@NOME_MES_ANO,
				@TRIMESTRE,
				@NOME_TRIMESTRE,
				@TRIMESTRE_ANO,
				@NOME_TRIMESTRE_ANO,
				@SEMESTRE,
				@NOME_SEMESTRE,
				@SEMESTRE_ANO,
				@NOME_SEMESTRE_ANO,
				@ANO,
				@TIPO_DIA
							   
			SET @DATAINICIAL = DATEADD(DAY,1,@DATAINICIAL)	
	
	END
END

truncate table DIM_DATA
EXEC SP_INSERT_DIM_DATA '2018-01-01', '2020-12-31'
--EXEC SP_INSERT_DIM_DATA '2018-08-01', '2020-07-31'
-- DATA FIM

-- HORA INÍCIO
DROP TABLE DIM_HORA

CREATE TABLE DIM_HORA (
	SK_HORA CHAR(4) NOT NULL,
	HORA SMALLINT NOT NULL,
	MINUTO SMALLINT NOT NULL,
	PADRAO CHAR NOT NULL,
	PERIODO VARCHAR(20) NOT NULL,
	PERIODO_ORDER SMALLINT NOT NULL,
	CONSTRAINT SK_HORA PRIMARY KEY (SK_HORA)
)
SELECT * FROM DIM_HORA

CREATE TABLE DIM_HORA 
(
    SK_HORA VARCHAR(4) NOT NULL PRIMARY KEY,
    HORA SMALLINT NOT NULL,
    MINUTO SMALLINT NOT NULL,
    PADRAO CHAR(2) NOT NULL,
    PERIODO VARCHAR(20) NULL,
    PERIODO_ORDER SMALLINT NULL
)

DECLARE @startdate DATETIME
DECLARE @enddate DATETIME
DECLARE @date DATETIME

SET @startdate = '1/1/2021 12:00:00 AM'
SET @enddate = '1/1/2021 23:59:59 PM'
SET @date = @startdate

WHILE @date <= @enddate
BEGIN
    INSERT INTO DIM_HORA 
        (SK_HORA, HORA, MINUTO, PADRAO, PERIODO, PERIODO_ORDER)
    VALUES 
        (
            REPLACE(CONVERT(VARCHAR(5), @date, 108), ':', ''),
            CONVERT(VARCHAR(2), @date, 108),
            DATEPART(mi, @date),
            CASE 
                WHEN DATEPART(hh, @date) BETWEEN 0 AND 11 THEN 'AM' 
                ELSE 'PM' 
            END,
            CASE
                WHEN DATEPART(hh, @date) BETWEEN 0 AND 5 THEN 'Madrugada'
                WHEN DATEPART(hh, @date) BETWEEN 6 AND 11 THEN 'Manhã'
                WHEN DATEPART(hh, @date) BETWEEN 12 AND 17 THEN 'Tarde'
                ELSE 'Noite'
            END,
            CASE
                WHEN DATEPART(hh, @date) BETWEEN 0 AND 5 THEN 1
                WHEN DATEPART(hh, @date) BETWEEN 6 AND 11 THEN 2
                WHEN DATEPART(hh, @date) BETWEEN 12 AND 17 THEN 3
                ELSE 4
            END 
        )

    SET @date = DATEADD(mi, 1, @date)
END

SELECT * FROM DIM_HORA

-- HORA FIM

-- FATO PRÉ INCRIÇÕES INÍCIO
CREATE TABLE FATO_PRE_INSCRICOES (
                SK_CANDIDATO INT NOT NULL,
                SK_PROCESSO INT NOT NULL,
                SK_CURSO INT NOT NULL,
                SK_DATA CHAR(8) NOT NULL,
                SK_HORA CHAR(4) NOT NULL,
                CONSTRAINT SK_FATO_PRE_INSCRICOES PRIMARY KEY (SK_CANDIDATO, SK_PROCESSO, SK_CURSO, SK_DATA, SK_HORA)
)

-- FATO PRÉ INSCRIÇÕES FIM

-- FATO INSCRIÇÕES INÍCIO
CREATE TABLE FATO_INSCRICOES (
                SK_CANDIDATO INT NOT NULL,
                SK_PROCESSO INT NOT NULL,
                SK_CURSO INT NOT NULL,
                SK_DATA CHAR(8) NOT NULL,
                SK_HORA CHAR(4) NOT NULL,
                BOLSA_ESTUDO INT NOT NULL,
                CALL_CENTER INT NOT NULL,
                CONSTRAINT SK_FATO_INSCRICOES PRIMARY KEY (SK_CANDIDATO, SK_PROCESSO, SK_CURSO, SK_DATA, SK_HORA)
)

-- FATO INSCRIÇÕES FIM

-- FATO INSCRIÇÕES PAGA INÍCIO
CREATE TABLE FATO_INSCRICOES_PAGAS (
    SK_CANDIDATO INT NOT NULL,
    SK_PROCESSO INT NOT NULL,
    SK_CURSO INT NOT NULL,
    SK_DATA CHAR(8) NOT NULL,
    SK_HORA CHAR(4) NOT NULL,
    SK_FORMA_PAGTO INT NOT NULL,
    CALL_CENTER INT NOT NULL,
    BOLSA_ESTUDO INT NOT NULL,
    VALOR DECIMAL(10) NOT NULL,
    CONSTRAINT SK_FATO_INSCRICOES_PAGAS PRIMARY KEY (SK_CANDIDATO, SK_PROCESSO, SK_CURSO, SK_DATA, SK_HORA, SK_FORMA_PAGTO)
)
-- FATO INSCRIÇÕES PAGA FIM