USE ST_Vestibular
-- CANDIDATO INÍCIO
CREATE VIEW VW_ST_CANDIDATO
	AS
SELECT DISTINCT
	CANDIDATO_ID,
	CANDIDATO
FROM 
	ST_vestibular

SELECT * FROM VW_ST_CANDIDATO
-- CANDIDATO FIM

-- CURSO INÍCIO
CREATE VIEW VW_ST_CURSO
	AS
SELECT DISTINCT
	CURSO_ID,
	CURSO
FROM
	ST_vestibular

SELECT * FROM VW_ST_CURSO
-- CURSO FIM

-- PROCESSO INÍCIO
CREATE VIEW VW_ST_PROCESSO
	AS
SELECT  DISTINCT
	PROCESSO_ID,
	PROCESSO,
	PERIODO_LETIVO
FROM 
	ST_vestibular

SELECT * FROM VW_ST_PROCESSO
-- PROCESSO FIM

-- FORMA P INÍCIO
CREATE VIEW VW_ST_FORMA_PAGAMENTO
	AS
SELECT DISTINCT
    FORMA_PAGAMENTO_ID,
    FORMA_PAGAMENTO
FROM
    ST_vestibular
WHERE 
    FORMA_PAGAMENTO_ID IS NOT NULL

SELECT * FROM VW_ST_FORMA_PAGAMENTO
-- FORMA P FIM

-- PRÉ-INCRIÇÕES INÍCIO

/*
13696 PRE-INSCRITOS
 9143 INSCRITOS
 5316 PAGOS
*/

CREATE VIEW VW_ST_PREINSCRICOES
AS
SELECT DISTINCT
	ISNULL(CANDIDATO_ID, -1) AS CANDIDATO_ID,
	ISNULL(CURSO_ID, -1) AS CURSO_ID,
	ISNULL(PROCESSO_ID, -1) AS PROCESSO_ID,
	DATA_PREINSCRICAO,
	REPLICATE('0', 4 - LEN(HORA_PREINSCRICAO)) + RTRIM(HORA_PREINSCRICAO) AS HORA_PREINSCRICAO
FROM 
	ST_vestibular
WHERE
	DATA_PREINSCRICAO IS NOT NULL


SELECT * FROM VW_ST_PREINSCRICOES
-- PRÉ-INSCRIÇÕES FIM

--INSCRIÇÕES INÍCIO
CREATE VIEW VW_ST_INSCRICOES
AS
SELECT DISTINCT
	ISNULL(CANDIDATO_ID, -1) AS CANDIDATO_ID,
	ISNULL(CURSO_ID, -1) AS CURSO_ID,
	ISNULL(PROCESSO_ID, -1) AS PROCESSO_ID,
	DATA_INSCRICAO,
	REPLICATE('0', 4 - LEN(HORA_INSCRICAO)) + RTRIM(HORA_INSCRICAO) AS HORA_INSCRICAO,
	CALL_CENTER,
	BOLSA_ESTUDO
FROM 
	ST_vestibular
WHERE
	DATA_INSCRICAO IS NOT NULL 

SELECT * FROM VW_ST_INSCRICOES
--INSCRIÇÕES FIM

--INSCRIÇÕES PAGAS INÍCIO
CREATE VIEW VW_ST_INSCRICOES_PAGAS
AS
SELECT DISTINCT
	ISNULL(CANDIDATO_ID, -1) AS CANDIDATO_ID,
	ISNULL(CURSO_ID, -1) AS CURSO_ID,
	ISNULL(PROCESSO_ID, -1) AS PROCESSO_ID,
	ISNULL(FORMA_PAGAMENTO_ID, -1) AS FORMA_PAGAMENTO_ID,
	DATA_PAGINSCRICAO,
	REPLICATE('0', 4 - LEN(HORA_PAGINSCRICAO)) + RTRIM(HORA_PAGINSCRICAO) AS HORA_PAGINSCRICAO,
	CALL_CENTER,
	BOLSA_ESTUDO,
	VALOR AS VALOR
FROM 
	ST_vestibular
WHERE
	DATA_PAGINSCRICAO IS NOT NULL   

SELECT * FROM VW_ST_INSCRICOES_PAGAS
--INSCRIÇÕES PAGAS FIM